# Generated by Django 4.0.4 on 2022-08-31 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Título')),
                ('numero', models.CharField(max_length=11, verbose_name='Título')),
                ('cpf', models.CharField(max_length=11, verbose_name='Título')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Título')),
                ('numero', models.CharField(max_length=11, verbose_name='Título')),
                ('cref', models.CharField(max_length=6, verbose_name='Título')),
            ],
        ),
        migrations.CreateModel(
            name='Maquinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Título')),
                ('numero', models.CharField(max_length=11, verbose_name='Título')),
            ],
        ),
    ]
